<?php include "includes/header.php";?>    

    <p>Ideally, in the business market in 2021, a responsive website should be used alongside a mobile app to capture all prospective targets. But, app development is both expensive and time-consuming. If having to go with one over the other, a responsive website may be the way to go. According to Vitaly Kuprenko on the Capturly Blog, “Responsive websites adapt their design to the screen of your device. No matter what the target device screen size is. It allows the web page to change its height and width and show correctly on any screen because of a ‘fluid’ layout and ‘fluid’ grid. (Kuprenko)” This suggests a user-friendly experience across the board, rather than targeting mobile customers exclusively.</p>
    <p>Though mobile apps are still crucial, and can’t be dismissed, if possible. Viktor Korol on the ThinkMobiles Blog makes a great point, saying “While your website is aimed at attracting new or occasional clients, your mobile app works with regular clients. A mobile app is notably good when a person needs to complete some goal. The well-designed app must give your client all opportunities to perform it just in a few taps or scrolls. (Korol)” Buildfire.com supports this, pointing out that “App usage accounts for about 27% of consumers mobile time, (Buildfire)” which is not a percentage that should be ignored. However, they also say “67% of mobile users said they would be more likely to make a purchase from a website than from an app. And the statistics show that this is true for most large purchases. Although, in-app purchases for small-ticket items remain strong. (Buildfire)”</p>
    <p>While responsive websites appear to be the way to go if having to choose one over the other, at the end of the day, it really comes down to what is best for one’s particular business. Sveta Cherednichenko at Mobindustry.net bolsters this, noting “Though this is a clear indicator that a business should be present on mobile devices, it doesn’t mean that users will spend that much time in your app. Most of this 90% of mobile traffic belongs to famous apps like Facebook, Instagram, and banking applications. Though traffic on mobile is huge, it doesn’t belong to apps only. The decision to create a mobile website or app depends on your domain, business processes, goals, and other factors like budget and deadline. (Cherednichenko)” Like anything else, considerable time, thought, research, and sense should be put into one’s endeavors before making any decisions. But, if cost is an issue, leaning towards responsive website versatility is advised.</p>
</section>
<!-- END LEFT COL -->

<!-- START RIGHT COL -->
<aside>
 <h3>Citations</h3>
    <p>Kuprenko, Vitaly. “Responsive Website or Mobile App? - How to Make the Right Choice.” Capturly Blog, 18 Sept. 2020 <a href="https://capturly.com/blog/responsive-website-or-mobile-app-how-to-make-the-right-choice" target="_blank">Capturely Blog</a></p>
    <p>Korol, Viktor. “Responsive Website vs Mobile App: Choose One or Both - 2021.” Thinkmobiles, 18 Apr. 2021 <a href="https://thinkmobiles.com/blog/responsive-website-vs-mobile-app" target="_blank">Thinkmobiles Blog</a></p>
    <p>BuildFire. “Responsive Websites vs. Web Apps And Native Apps - And Why It Matters.” BuildFire, 30 Jan. 2018 <a href="https://buildfire.com/responsive-websites-vs-web-apps-native-apps-matters" target="_blank">BuildFire.com</a></p>
    <p>Cherednichenko, Sveta. “Mobile App, Responsive Website, or Something in Between: What to Choose for Your Business.” Mobindustry, 27 Aug. 2019 <a href="https://www.mobindustry.net/mobile-app-responsive-website-or-something-in-between-what-to-choose-for-your-business-in-2019/" target="_blank">Mobindustry Blog</a></p>
</aside>
<!-- END RIGHT COL -->
<?php include "includes/footer.php";?>